aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  web: web/src
  root: D:\work\IdeaProjects\gin-vue-admin
  server: server
  module: github.com/flipped-aurora/gin-vue-admin/server
  ai-path: https://ai.gin-vue-admin.com/{FUNC}/jsxuehua/7b8442f9-bca9-4bfd-8808-7b4f1b83fbeb
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
  s3-force-path-style: false
  disable-ssl: false
captcha:
  key-long: 4
  img-width: 240
  img-height: 80
  open-captcha: 3
  open-captcha-timeout: 3600
cloudflare-r2:
  bucket: xxxx0bucket
  base-url: https://gin.vue.admin.com
  path: uploads
  account-id: xxx_account_id
  access-key-id: xxx_key_id
  secret-access-key: xxx_secret_key
cors:
  mode: ""
  whitelist: []
db-list:
  - type: ""
    alias-name: ""
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
    disable: true
disk-list:
  - mount-point: /
email:
  to: xxx@qq.com
  from: xxx@163.com
  host: smtp.163.com
  secret: xxx
  nickname: test
  port: 465
  is-ssl: true
excel:
  dir: ./resource/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  signing-key: 78c0f08f-9663-4c9c-a399-cc4ec36b8112
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
local:
  path: uploads/file
  store-path: uploads/file
mcp:
  name: GVA_MCP
  version: v1.0.0
  sse_path: /sse
  message_path: /message
  url_prefix: ""
minio:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  use-ssl: false
  base-path: ""
  bucket-url: http://host:9000/yourBucketName
mongo:
  coll: ""
  options: ""
  database: ""
  username: ""
  password: ""
  auth-source: ""
  min-pool-size: 0
  max-pool-size: 100
  socket-timeout-ms: 0
  connect-timeout-ms: 0
  is-zap: false
  hosts:
    - host: ""
      port: ""
mssql:
  prefix: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  path: ""
  engine: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
mysql:
  prefix: ""
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gin_vue_admin
  username: root
  password: Gva123456!
  path: 49.235.40.39
  engine: ""
  log-mode: error
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
nfc-relay:
  websocket-pong-wait-sec: 60
  websocket-max-message-bytes: 2048
  websocket-write-wait-sec: 10
  hub-check-interval-sec: 60
  session-inactive-timeout-sec: 300
  security:
    enable-tls: false
    cert-file: ./certs/server.crt
    key-file: ./certs/server.key
    force-tls: false
    enable-audit-encryption: false
    encryption-algorithm: AES-256-GCM
    audit-key-rotation-hours: 0
    enable-compliance-audit: false
    enable-deep-inspection: false
    max-transaction-amount: 0
    blocked-merchant-categories: []
    enable-e2e-encryption: true
    key-exchange-method: ECDH
    enable-anti-replay: true
    replay-window-ms: 30000
    max-nonce-cache: 10000
    max-message-size: 4096
    enable-input-sanitize: true
    require-client-cert: false
    client-ca-file: ./certs/ca.crt
oracle:
  prefix: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  path: ""
  engine: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
pgsql:
  prefix: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  path: ""
  engine: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  access-key: ""
  secret-key: ""
  use-https: false
  use-cdn-domains: false
redis:
  name: nfc
  addr: 49.235.40.39:6379
  password: "Gva123456!"
  db: 0
  useCluster: false
  clusterAddrs:
    - 172.21.0.3:7000
redis-list:
  - name: cache
    addr: 49.235.40.39:6379
    password: xuehua123
    db: 0
    useCluster: false
    clusterAddrs:
      - 172.21.0.3:7000
      - 172.21.0.4:7001
      - 172.21.0.2:7002
sqlite:
  prefix: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  path: ""
  engine: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
system:
  db-type: mysql
  oss-type: local
  router-prefix: ""
  addr: 8888
  iplimit-count: 15000
  iplimit-time: 3600
  use-multipoint: false
  use-redis: true
  use-mongo: false
  use-strict-auth: false
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
zap:
  level: debug
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
  retention-day: -1
# MQTT配置
mqtt:
  host: 192.168.50.194
  port: 8883
  username: nfc_server
  password: xuehua123
  client-id: nfc-relay-server
  qos: 1
  keep-alive: 60
  clean-session: true
  use-tls: true
  api:
    host: 192.168.50.194          # EMQX管理API主机，通常与MQTT主机相同
    port: 18083                 # EMQX管理API端口，默认18083
    username: 30ad44d40f17065d  # EMQX API Key (用作Basic Auth用户名)
    password: JyXjEERdfHijUvzh9BtcJWljL9B4xOatExqgglQfaa5qM # EMQX Secret Key (用作Basic Auth密码)
    use-tls: false              # 管理API是否使用TLS
  nfc-relay:
    topic-prefix: nfc_relay
    heartbeat-interval: 30
    heartbeat-timeout: 60
    message-timeout: 30
    max-message-size: 4096
    retry-attempts: 3
    retry-interval: 5
    enable-permission-control: true
    enable-metrics: true
    metrics-interval: 60
