name: 自动部署到服务器

on:
  push:
    branches: [ main, dev-mqtt ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 部署到服务器
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # 进入项目目录（如果不存在则克隆）
          if [ ! -d "/opt/gin-vue-admin" ]; then
            sudo mkdir -p /opt/gin-vue-admin
            cd /opt/gin-vue-admin
            git clone https://github.com/${{ github.repository }} .
          else
            cd /opt/gin-vue-admin
            git pull origin main
          fi
          
          # 停止旧服务
          sudo docker-compose -f deploy/docker-compose.yml down || true
          
          # 构建并启动新服务
          sudo docker-compose -f deploy/docker-compose.yml up -d --build
          
          # 等待服务启动
          sleep 30
          
          # 检查服务状态
          sudo docker-compose -f deploy/docker-compose.yml ps
          
          echo "部署完成！访问地址: http://${{ secrets.SERVER_HOST }}" 